apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: kafka-example
spec:
  # image: "haroldo89/flink-demo-1-11:0.0.9"
  image: "haroldo89/flink-kafka:0.0.9"
  # image: "haroldo89/flink-kafka-error:0.0.2"
  flinkVersion: v1_13
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/demo/streaming/flinkdemo.jar
    parallelism: 1
    upgradeMode: stateless